# permissions for end users to edit secretsynchronizers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretsynchronizer-editor-role
rules:
- apiGroups:
  - synchronizer.a1tan
  resources:
  - secretsynchronizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - synchronizer.a1tan
  resources:
  - secretsynchronizers/status
  verbs:
  - get
