# permissions for end users to view secretsynchronizers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretsynchronizer-viewer-role
rules:
- apiGroups:
  - synchronizer.a1tan
  resources:
  - secretsynchronizers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - synchronizer.a1tan
  resources:
  - secretsynchronizers/status
  verbs:
  - get
