apiVersion: synchronizer.a1tan/v1alpha1
kind: SecretSynchronizer
metadata:
  labels:
    app: secretsynchronizer
  name: secretsynchronizer
  namespace: argocdsecretsynchronizer-system
spec:
  size: 1
  prune: true